apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-app-configmap
data:
  .env: |-
    API_SERVER_PORT=8080
    TOKEN_KEY=asdadsd5v1s6d1vs6dcd
    CURRENT_DB=postgres

    POSTGRES_HOST=postgres-service
    POSTGRES_PORT=5432
    POSTGRES_USER=postgres
    POSTGRES_PASSWORD=secret
    POSTGRES_DB=postgres
    POSTGRES_SSL_MODE=disable
