apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: gcr.io/todo-service-388108/chat-chat-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: chat-app-configmap
          imagePullPolicy: Always
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-volume
          configMap:
            name: chat-app-configmap
