version: '3'
services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file:
      - C:/Users/Валентина/GolangProject/Chat/.env
    volumes:
      - C:/Users/Валентина/GolangProject/Chat/.env:/app/.env
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - C:/Users/Валентина/GolangProject/Chat/.env
    ports:
      - 5432:5432
    volumes:
      - C:/Users/Валентина/GolangProject/Chat/internal/database/psql:/var/lib/postgresql/data

