apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_HOST: cG9zdGdyZXMtc2VydmljZQ==
  POSTGRES_PORT: NTQzMiA=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: c2VjcmV0
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_SSL_MODE: ZGlzYWJsZQ==
