name: Deploy to GCP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: todo-service-388108

      - name: Configure Docker CLI
        run: |
          echo ${{ secrets.GCR_TOKEN }} | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build Docker image
        run: |
          docker build -t gcr.io/todo-service-388108/chat-chat-app:latest .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/todo-service-388108/chat-chat-app:latest

      - name: Set up kubectl
        run: |
          gcloud components install kubectl

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/chat-app-deployment chat-app=gcr.io/todo-service-388108/chat-chat-app:latest
